[package]
name = "aassethook-capi"
version = "0.1.0"
authors = ["Jeff Dileo"]

[lib]
name = "aassethook_capi"
crate-type = ["dylib"]

[dependencies]
interpolate_idents = "0.1.3"
libc = "0.2.18"
regex = "0.1"
lazy_static = "0.1.*"
libloading = "0.3"
memmap = "0.5.0"

